branch-defaults:
  develop:
    environment: Isiscb-celery-staging-p312-env
global:
  application_name: isiscb-celery-staging-p312
  default_platform: Docker running on 64bit Amazon Linux 2023/4.7.2
  default_region: us-west-2
  sc: git
